apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ontos.fullname" . }}-config
  labels:
    {{- include "ontos.labels" . | nindent 4 }}
data:
  NEO4J_URI: {{ default "" (get (.Values.runtime.neo4j) "uri") | quote }}
{{- if .Values.ontology.configMap.create }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ontos.fullname" . }}-ontology
  labels:
    {{- include "ontos.labels" . | nindent 4 }}
data:
  starter.yaml: |
{{ .Values.ontology.configMap.yaml | indent 4 }}
{{- end }}
